### PR TITLE
Ensure that clusters' apiServiceURL is honored for kubeapps cluster.

### LINKED ISSUE #5999: Unauthorized response in GetPackageRepositorySummaries
```
Invalid GetPackageRepositorySummaries response from the plugin helm.packages: rpc error: code = Unauthenticated desc = Authorization required to get the AppRepository 'all' due to 'Unauthorized'
```

We're trying to upgrade to kubeapps 2.6.3 (latest release) and I've encountered a strange bug when trying to load the `Catalog`.

Seemingly due to an Unauthorized GRPC response, the dashboard redirects back to `/` and I end up right where I started (i.e. main dashboard page viewing applications).

1. Load kubeapps
2. Click `Catalog`
3. Redirected back to dashboard

image
image
image

Is there some new configuration now that we need to do to permit our users to view package repositories?

We have 2 `AppRepository` configured in this cluster (BTW what is the difference to the "PackageRepository" concept?):

```
(⎈ default:kubeapps)mcampbell-1 :: coreweave/k8s-services/dev ‹master*› » k neat get apprepository
apiVersion: v1
items:
- apiVersion: kubeapps.com/v1alpha1
  kind: AppRepository
  metadata:
    annotations:
      meta.helm.sh/release-name: kubeapps
      meta.helm.sh/release-namespace: kubeapps
    labels:
      app.kubernetes.io/instance: kubeapps
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kubeapps
      helm.sh/chart: kubeapps-12.2.1-dev0
    name: ant-repo
    namespace: kubeapps
  spec:
    syncJobPodTemplate:
      spec:
        securityContext:
          runAsUser: 1001
    type: helm
    url: http://charts.tenant-rizzo.ord1.ingress.coreweave.cloud/
- apiVersion: kubeapps.com/v1alpha1
  kind: AppRepository
  metadata:
    annotations:
      meta.helm.sh/release-name: kubeapps
      meta.helm.sh/release-namespace: kubeapps
    labels:
      app.kubernetes.io/instance: kubeapps
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kubeapps
      helm.sh/chart: kubeapps-12.2.1-dev0
    name: coreweave
    namespace: kubeapps
  spec:
    syncJobPodTemplate:
      spec:
        securityContext:
          runAsUser: 1001
    type: helm
    url: http://helm.corp.ingress.ord1.coreweave.com/
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

### PR DESCRIPTION
**Pull request by absoludity**
### Description of the change

After some testing of the previous PR, we found the issue is actually that kubeapps assumes the cluster on which Kubeapps is installed will never have an APIServiceURL set in the configuration (since it can be accessed via the in-cluster configuration at https://kubernetes.default).

As it turns out, some users need to set the APIServiceURL of the cluster on which Kubeapps is installed because they use a proxy in front of the API server for authentication purposes, so it's important that Kubeapps also use this.

### Applicable issues

- fixes #5999

### CODE REVIEW

File: pkg/kube/cluster_config.go [hunk 1]
```diff
@@ -137,7 +137,10 @@ func NewClusterConfig(inClusterConfig *rest.Config, userToken string, cluster st
 		return config, nil
 	}
 
-	if cluster == clustersConfig.KubeappsClusterName {
+	// We cannot assume that if the cluster is the kubeapps cluster that we simply return
+	// the incluster config, because some users set proxies in front of their clusters in
+	// which case the incluster kubernetes.default will skip the proxy.
```
Comment (mecampbellsoup) [inline pkg/kube/cluster_config.go:142]: Good comment.

**Review by mecampbellsoup — APPROVED** [review]
Love how small this PR is 😄 LGTM!

Also tested on our setup and things are working again.
