### PR TITLE
Fix for GKE CI pipeline

### LINKED ISSUE #5421: CI failing in GKE
**Describe the bug**
The prerelease flow is reporting some errors due to chartmuseum not being able to get deployed/exposed-.

````
Successfully packaged chart and saved it to: /home/circleci/project/kubeapps-apache-8.6.2.tgz
>> Pushing chart 'kubeapps-apache-8.6.2.tgz' (apache v8.6.2) to chart museum at chart-museum and IP 172.18.0.2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:10 --:--:--     0
curl: (28) Failed to connect to 172.18.0.2 port 80: Connection timed ou
````

**To Reproduce**
Run the `prerelease` CI workflow.

**Expected behavior**
The connection to chartmuseum should work.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
Example: https://app.circleci.com/pipelines/github/vmware-tanzu/kubeapps/8858/workflows/541ae720-bf05-4ef4-bc3b-feb18850e468/jobs/98778

### PR DESCRIPTION
**Pull request by castelblanque**
### Description of the change

This PR fixes the CI pipeline in GKE at the point of accesing the Chart Museum.
In #5337, an ingress was added to use Chart Museum, instead of using a `port-forward`.
Nginx ingress is installed in the Kind clusters created, but not on GKE cluster. Hence this PR.

Example of [passing GKE pipeline](https://app.circleci.com/pipelines/github/vmware-tanzu/kubeapps/8897/workflows/e402e6b2-2778-4ea9-a176-bb5e788c2257).

### Benefits

GKE CI pipelines will work with chart museum without `port-forward`.

### Possible drawbacks

Chart museum will be exposed through an Ingress in GKE clusters while testing. But Chart museum itself has authentication, so it should not be a problem.

### Applicable issues

- fixes #5421

### CODE REVIEW

File: script/install-nginx.sh [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+helm repo update
+helm install -n nginx-ingress --create-namespace nginx-ingress ingress-nginx/ingress-nginx
+
+# Wait for load balancer to get the IP
+LB_IP=""
+while [ -z $LB_IP ]; do
+  echo "Waiting for external IP"
+  LB_IP=$(kubectl -n nginx-ingress get service nginx-ingress-ingress-nginx-controller --template="{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}")
+  [ -z "$LB_IP" ] && sleep 10
+done
```
Comment (castelblanque) [inline script/install-nginx.sh:21]: Ideally we would like this to have a max retries limitation.

File: script/install-nginx.sh [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+# SPDX-License-Identifier: Apache-2.0
+
+set -o errexit
+set -o nounset
+set -o pipefail
+
+echo "Instaling Nginx"
+helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
+helm repo update
+helm install -n nginx-ingress --create-namespace nginx-ingress ingress-nginx/ingress-nginx
```
Comment (antgamdia) [inline script/install-nginx.sh:13]: I guess we don't need the annotations we use to add for Kubeapps itself, no?

**Review by antgamdia — APPROVED** [review]
Great! Thanks a lot for the fix!

@beni0888, do you know if these changes are also applicable to the recent GH action?

File: script/install-nginx.sh (hunk 2 above)
Comment (castelblanque) [reply script/install-nginx.sh:13]: Do you mean the buffers setup? Not sure what values come installing Nginx with Helm.
If annotations don't cause harm, I would leave them by now.

File: script/chart-museum.sh [hunk 3]
```diff
@@ -8,7 +8,7 @@ CHARTMUSEUM_PWD=${CHARTMUSEUM_PWD:-"password"}
 CHARTMUSEUM_NS=${CHARTMUSEUM_NS:-"chart-museum"}
 CHARTMUSEUM_VERSION=${CHARTMUSEUM_VERSION:-"3.9.0"}
 CHARTMUSEUM_HOSTNAME=${CHARTMUSEUM_HOSTNAME:-"chart-museum"}
-CHARTMUSEUM_IP=${DEX_IP}
+CHARTMUSEUM_IP=${LOAD_BALANCER_IP}
```
Comment (beni0888) [inline script/chart-museum.sh:11]:
```suggestion
CHARTMUSEUM_IP=${LOAD_BALANCER_IP:?"Not provided"}
```
I would add this check to make the script fail out loud when the env variable is not provided, a avoid some potential headaches 😅

**Comment by castelblanque** [comment]
> do you know if these changes are also applicable to the recent GH action?

This branch already contains the GH pipeline. It is actually failing at one step: `push_dev_images`. Looking at it with @beni0888 .

File: script/install-nginx.sh [hunk 4]
```diff
@@ -0,0 +1,22 @@
+#!/usr/bin/env bash
+
+# Copyright 2018-2022 the Kubeapps contributors.
+# SPDX-License-Identifier: Apache-2.0
+
+set -o errexit
+set -o nounset
+set -o pipefail
```
Comment (beni0888) [inline script/install-nginx.sh:8]:
```suggestion
set -euo pipefail
```
Nitpick, this can be done with a oneliner.

File: script/chart-museum.sh (hunk 3 above)
Comment (castelblanque) [reply script/chart-museum.sh:11]: I did not add it here on purpose. Instead added the check below, inside function `pushChartToChartMuseum`, as it is the only operation that needs the IP.

File: script/install-nginx.sh (hunk 1 above)
Comment (beni0888) [reply script/install-nginx.sh:21]: yeah, I think we should add it to avoid potential headaches 😄

**Review by beni0888 — APPROVED** [review]
LGTM!

File: script/chart-museum.sh (hunk 3 above)
Comment (beni0888) [reply script/chart-museum.sh:11]: Yeah, I saw after adding my comment 🤐

**Comment by beni0888** [comment]
> Great! Thanks a lot for the fix!
> 
> @beni0888, do you know if these changes are also applicable to the recent GH action?

At this moment, the GKE-related jobs haven't been migrated to the GHA workflow, so these changes shouldn't affect it.

**Comment by castelblanque** [comment]
Merging, as only one step of new GH actions pipeline is failing (`Kubeapps general pipeline / push_dev_images`).
Not relevant by now.

File: script/install-nginx.sh (hunk 1 above)
Comment (castelblanque) [reply script/install-nginx.sh:19]: There is the timeout of the pipeline run itself that will kick in for now. Will try to tackle it in a further PR.
