### PR TITLE
Fix script to fetch the latest published container in dockerhub

### LINKED ISSUE #6220: Release script uses non-existent location for container tags
**Describe the bug**

Our current release action tries to establish the latest tag for each upstream bitnami kubeapps image by querying the GH API for container repositories that no longer exist. In particular, these lines:

https://github.com/vmware-tanzu/kubeapps/blob/1e4634e3f85401f75d06dd90f5fe6216f8ffaff2/script/chart_sync_utils.sh#L112-L114

attempt to reference, for example, a GH repo called `bitnami/bitnami-docker-kubeapps-dashboard`, which was deleted some months ago when the individual container repos were moved into `bitnami/containers`.

This change was [announced in July last year](https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html), but the repos must have only been removed/deleted recently.

**To Reproduce**

Run the release action and find i[t fails with the less than obvious error](https://github.com/vmware-tanzu/kubeapps/actions/runs/4749214983/jobs/8436752821):

```
Replacing dashboard...
jq: error (at <stdin>:4): Cannot index object with number
Error: Process completed with exit code 5.
```

**Expected behavior**

The upstream PR should be created without issue.

### PR DESCRIPTION
**Pull request by antgamdia**
### Description of the change

This PR is to actually fix #6220 by fetching from DockerHub the more recent (!=latest) published tag. I'm removing the workaround performed in https://github.com/vmware-tanzu/kubeapps/pull/6237. 

### Benefits

The script will continue to work as initially expected.

### Possible drawbacks

N/A

### Applicable issues

- fixes #6220 

### Additional information

N/A

### CODE REVIEW

File: script/chart_sync_utils.sh [hunk 1]
```diff
@@ -109,22 +108,21 @@ replaceImage_latestToProduction() {
...
-    # See https://github.com/vmware-tanzu/kubeapps/issues/6220
-    # We may need to update to use dockerhub if we want the most recent tag
-    # explicitly. For now, just create the PR with the latest tag.
-    # local tag
-    # tag=$(curl "${curl_opts[@]}" "https://api.github.com/repos/bitnami/${repoName}/tags" | jq -r '.[0].name')
+    # Get the latest tag from the bitnami repository in DockerHub.
+    # Assumption: the more recent tag is the second one in the list after a reverse alphabetical sorting,
+    # first one is "latest", which we don't actually want.
+    local tag
+    tag=$(curl "${curl_opts[@]}" "https://hub.docker.com/v2/namespaces/bitnami/repositories/${repoName}/tags" | jq -r '.results[].name' | sort -r --version-sort | sed -n "2 {p;q}")
```
Comment (absoludity) [inline script/chart_sync_utils.sh:115]: Nice - I'd not looked at switching from the non-existent GH repos to checking the dockerhub repo instead.

**Review by absoludity — APPROVED** [review]
