### PR TITLE
Add fix for Helm charts versions ordering

### LINKED ISSUE #4950: helm direct plugin returns incorrect response for GetAvailablePackageVersions
Reproduction steps:
1) install kubeapps in your kind cluster with helm direct plugin. I did it via
```
helm upgrade kubeapps ./chart/kubeapps --install --namespace kubeapps --create-namespace \
         --set "packaging.helm.enabled=true" \
         --set "packaging.flux.enabled=false" \
          --wait
```
after a pull yesterday (6/23/22)
2. from https://stefanprodan.github.io/podinfo wget these files
podinfo-6.0.0.tgz podinfo-6.0.3.tgz podinfo-5.2.1.tgz podinfo-6.1.6.tgz podinfo-6.1.5.tgz podinfo-6.1.4.tgz podinfo-6.1.3.tgz (total of 7)
3. with a web browser login to demo.goharbor.io [admin/Harbor12345]
4. create a public project 'test-oci-1'
5. in terminal window `helm registry login -u admin -p Harbor12345 demo.goharbor.io`
6. for each file in (2) 
`helm push $file oci://demo.goharbor.io/test-oci-1`
7. 
`kubectl port-forward --namespace kubeapps service/kubeapps 8080:80`
create helm-direct OCI registry:
`curl -i 'http://localhost:8080/api/v1/clusters/default/namespaces/default/apprepositories' -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Authorization: Bearer $token' -H 'Origin: http://localhost:8080' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Referer: http://localhost:8080/' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' --data-raw '{"appRepository":{"name":"podinfo","repoURL":"https://demo.goharbor.io/test-oci-1","authHeader":"Basic YWRtaW46SGFyYm9yMTIzNDU=","authRegCreds":"","type":"oci","description":"","customCA":"","syncJobPodTemplate":{},"registrySecrets":[],"ociRepositories":["podinfo"],"tlsInsecureSkipVerify":false,"passCredentials":false}}'
`
8. 
```
kubectl -n kubeapps port-forward svc/kubeapps-internal-kubeappsapis 8080:8080
grpcurl -plaintext -d '{"available_package_ref": {"context": {"cluster": "default", "namespace": "default"}, "plugin": {"name": "helm.packages", "version": "v1alpha1"}, "identifier": "podinfo/podinfo"}}' -H "Authorization: $token" localhost:8080 kubeappsapis.core.packages.v1alpha1.PackagesService.GetAvailablePackageVersions

{
  "packageAppVersions": [
    {
      "pkgVersion": "6.1.4",
      "appVersion": "6.1.4"
    },
    {
      "pkgVersion": "6.1.6",
      "appVersion": "6.1.6"
    },
    {
      "pkgVersion": "6.1.3",
      "appVersion": "6.1.3"
    },
    {
      "pkgVersion": "5.2.1",
      "appVersion": "5.2.1"
    },
    {
      "pkgVersion": "6.0.3",
      "appVersion": "6.0.3"
    },
    {
      "pkgVersion": "6.0.0",
      "appVersion": "6.0.0"
    }
  ]
}

```
this list is not correct. 6.1.5 is missing and 6.1.3 should not be in the response

### PR DESCRIPTION
**Pull request by castelblanque**
Signed-off-by: Rafa Castelblanque <rcastelblanq@vmware.com>

### Description of the change

This bugfix tackles the issue of `GetAvailablePackageVersions` in Helm direct plugin not returning the correct versions list when the input versions are not ordered.

We had all input values in our tests correctly sorted, which might not be the case on runtime.
[See here.](https://github.com/vmware-tanzu/kubeapps/blob/main/cmd/kubeapps-apis/plugins/pkg/pkgutils/pkgutils_test.go#L31)

Solution done here is to sort versions first thing in [PackageAppVersionsSummary](https://github.com/vmware-tanzu/kubeapps/blob/main/cmd/kubeapps-apis/plugins/pkg/pkgutils/pkgutils.go#L57).

### Benefits

Versions returned by `GetAvailablePackageVersions` should be correct now.

### Possible drawbacks

Solution modifies `pkgutils.PackageAppVersionsSummary` function, which applies to Flux plugin as well, although it should not break anything.

### Applicable issues

- fixes #4950

### CODE REVIEW

File: cmd/kubeapps-apis/plugins/pkg/pkgutils/pkgutils_test.go [hunk 1]
```diff
@@ -342,6 +342,27 @@ func TestPackageAppVersionsSummary(t *testing.T) {
 				Minor: 0,
 				Patch: 0},
 		},
+		{
+			name: "it includes latest versions in right order",
```
Comment (antgamdia) [inline cmd/kubeapps-apis/plugins/pkg/pkgutils/pkgutils_test.go:346]:
```suggestion
			name: "it includes latest versions ordered (descending) by package version",
```

**Review by antgamdia — APPROVED** [review]
Great, thanks! Do you know if there exists the same problem in the InstalledPkgSummaries response ?

**Comment by castelblanque** [comment]
> Do you know if there exists the same problem in the InstalledPkgSummaries response ?

The defective function (`PackageAppVersionsSummary`) is not being invoked from the InstalledPkgSummaries. So I don't think there's a problem unless the code is repeated or `versionInSummary/versionsInSummary` is named alternatively somewhere else.
