### PR TITLE
Use annotations instead of a fixed manifest in Nginx

### LINKED ISSUE #3844: Use annotations to modify the ingress-controller config
### Description:

I noticed we have been using a customized version of the nginx for Kind ingress-controller in which explicitly modified the buffer size.

I wonder whether we should be passing this config using annotations instead of maintaining the whole set of nginx manifests in our repo.

We should be able to replace [this file](https://github.com/kubeapps/kubeapps/blob/master/docs/user/manifests/ingress-nginx-kind-with-large-proxy-buffers.yaml) with:

```yaml
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/proxy-buffers: "4"
```

If so, we should add this fragment in the readme or FAQ to help other people solve their ingress issues.

### PR DESCRIPTION
**Pull request by antgamdia**
### Description of the change

This PR removes the fiex nginx ingress controller manifest file we were using and, instead, makes use of the upstream version + adds the proper annotations (required for what https://github.com/vmware-tanzu/kubeapps/pull/1944 was aimed to).

### Benefits

We will get rid of a fixed and manually maintained yaml manifest.

### Possible drawbacks

Perhaps a less determinist CI runs? But if it becomes a problem, we can also fix the version in CI.

### Applicable issues

- fixes #3844

### Additional information

N/A

### CODE REVIEW

**Comment by antgamdia** [comment]
Marking as a draft as it is not urgent and it is failing somehow (although I couldn't reproduce it even ssh-ing to the circle ci runner).

````
Error: Ingress.extensions "kubeapps-ci" is invalid: [metadata.annotations: Invalid value: "\"nginx.ingress.kubernetes.io/proxy-buffers\"": prefix part a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.annotations: Invalid value: "\"nginx.ingress.kubernetes.io/proxy-buffers\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), metadata.annotations: Invalid value: "\"nginx.ingress.kubernetes.io/proxy-read-timeout\"": prefix part a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.annotations: Invalid value: "\"nginx.ingress.kubernetes.io/proxy-read-timeout\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), metadata.annotations: Invalid value: "\"kubernetes.io/ingress.class\"": prefix part a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.annotations: Invalid value: "\"kubernetes.io/ingress.class\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'), metadata.annotations: Invalid value: "\"nginx.ingress.kubernetes.io/proxy-buffer-size\"": prefix part a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.annotations: Invalid value: "\"nginx.ingress.kubernetes.io/proxy-buffer-size\"": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')]
````

File: script/e2e-test.sh [hunk 1]
```diff
@@ -266,6 +266,10 @@ if [ "$USE_MULTICLUSTER_OIDC_ENV" = true ]; then
     "--set" "ingress.hostname=localhost"
     "--set" "ingress.tls=true"
     "--set" "ingress.selfSigned=true"
+    "--set" "ingress.annotations.\"kubernetes\.io\/ingress\.class\"=nginx"
+    "--set" "ingress.annotations.\"nginx\.ingress\.kubernetes\.io\/proxy-buffer-size\"=8k"
+    "--set" "ingress.annotations.\"nginx\.ingress\.kubernetes\.io\/proxy-read-timeout\"=600.0"
+    "--set" "ingress.annotations.\"nginx\.ingress\.kubernetes\.io\/proxy-buffers\"=4.0"
```
Comment (castelblanque) [inline script/e2e-test.sh:272]: As Helm allows to pass multiple input values files, do you think that this would work? Tested locally and it did, who knows in the E2E CI?

```suggestion
    "--values" "${INGRESS_VALUES_FILE}"
```

Where `INGRESS_VALUES_FILE` would be the path to this Yaml file:

```
ingress:
  hostname: localhost
  tls: true
  selfSigned: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: 8k
    nginx.ingress.kubernetes.io/proxy-buffers: "4.0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600.0"

```

In this way we don't have to escape everything.

Comment (antgamdia) [reply script/e2e-test.sh:272]: Oh, that's another approach, good idea. If you already have the changes locally, please push them to this branch (as maintainers can edit PRs) to see if it passes and we can also close this one. Really looking forward to clean up the bunch of open PRs we have, haha

**Comment by castelblanque** [comment]
@antgamdia My proposal works, see [here](https://app.circleci.com/pipelines/github/antgamdia/kubeapps/2614/workflows/9022ba9a-74ed-44fa-b17e-27c88dfb1b2f).
Please review and merge if you think it is fine.

File: script/e2e-test.sh [hunk 2]
```diff
@@ -260,16 +281,12 @@ img_flags=(
...
 if [ "$USE_MULTICLUSTER_OIDC_ENV" = true ]; then
   multiclusterFlags=(
     "--set" "ingress.enabled=true"
-    "--set" "ingress.hostname=localhost"
-    "--set" "ingress.tls=true"
-    "--set" "ingress.selfSigned=true"
-    "--set" "ingress.annotations.\"kubernetes\.io\/ingress\.class\"=nginx"
-    "--set" "ingress.annotations.\"nginx\.ingress\.kubernetes\.io\/proxy-buffer-size\"=8k"
-    "--set" "ingress.annotations.\"nginx\.ingress\.kubernetes\.io\/proxy-read-timeout\"=600.0"
-    "--set" "ingress.annotations.\"nginx\.ingress\.kubernetes\.io\/proxy-buffers\"=4.0"
```
Comment (antgamdia) [inline script/e2e-test.sh]: I'd rather move all the `ingress.xxx` flags to the file OR just the `ingress.annotations.xxx`, but leaving the enabled=true as a `--set` and the rest on the file... seems a bit odd, no? 

I'm for moving just the annotations, but see what you think.

Thanks for the fix, btw!

Comment (castelblanque) [reply script/e2e-test.sh]: Ok, initially I left it there on purpose to clearly show that the ingress was enabled. Let's have everything related to ingress in that additional file, it is strange to have ingress settings scattered. WDYT?

**Review by beni0888 — APPROVED** [review]
